### ISSUE TITLE
contact information for CoC or similar

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day#19]
We should have a page with information how to contact someone immediately or directly (beyond https://www.mdanalysis.org/pages/conduct/ ).

I'd suggest

- @orbeckst (my work phone number (which goes to my mobile) and email)
- @jennaswa (email)

**Comment by jennaswa** [comment]
This text has been sent out in emails to participants:

All workshop participants and members of the MDAnalysis community must abide by the [MDAnalysis Code of Conduct](https://www.mdanalysis.org/pages/conduct/) (CoC). If at any point you see or experience something that makes you uncomfortable, you may fill out the [reporting form](https://docs.google.com/forms/d/e/1FAIpQLSeID-DiFMbXAHFeeiNgPKiCoa3FwA5I_92xE9cqlZB-3J49zA/viewform?c=0&w=1) or contact any of the CoC committee members (Jenna Swarthout Goddard, Micaela Matta, Richard Gowers). *NOTE: Our names are linked to our emails.*

To avoid publicizing phone numbers/emails, I could add your information @orbeckst to the [next email communication](https://docs.google.com/document/d/102tRuM--8OD0uKoBfdcsSIFvOjJmvmzM9Srq3LbgA4g/edit?usp=sharing), and we could direct people to that email for our contact information during the introduction (but listing you and I as ombudspeople for the event).

**Comment by orbeckst** [comment]
Drafting something to include in the materials:

## Code of Conduct and Reporting

All workshop participants and members of the MDAnalysis community must abide by the [MDAnalysis Code of Conduct](https://www.mdanalysis.org/pages/conduct/) (CoC). If at any point you see or experience something that makes you uncomfortable, you may fill out the [reporting form](https://docs.google.com/forms/d/e/1FAIpQLSeID-DiFMbXAHFeeiNgPKiCoa3FwA5I_92xE9cqlZB-3J49zA/viewform?c=0&w=1) or contact any of the CoC committee members directly (Jenna Swarthout Goddard <EMAIL JSG>, Micaela Matta <EMAIL MM>, Richard Gowers <EMAIL RG>).

At and during the workshop, you can contact the following people with any concerns you may have: 
* Oliver Beckstein (talk to him in person or email orbeckst@mdanalysis.org or call +1 480 727 9765 or `@orbeckst` on Discord)
* Jenna Swarthout Goddard (email: , `@jennaswa` on Discord) 
* Irfan Alibay (talk to him in person or email: , `@highspeedmode` on Discord)

**Comment by IAlibay** [comment]
> Drafting something to include in the materials:
> 
> ## Code of Conduct and Reporting
> 
> All workshop participants and members of the MDAnalysis community must abide by the [MDAnalysis Code of Conduct](https://www.mdanalysis.org/pages/conduct/) (CoC). If at any point you see or experience something that makes you uncomfortable, you may fill out the [reporting form](https://docs.google.com/forms/d/e/1FAIpQLSeID-DiFMbXAHFeeiNgPKiCoa3FwA5I_92xE9cqlZB-3J49zA/viewform?c=0&w=1) or contact any of the CoC committee members directly (Jenna Swarthout Goddard <EMAIL JSG>, Micaela Matta <EMAIL MM>, Richard Gowers <EMAIL RG>).
> 
> At and during the workshop, you can contact the following people with any concerns you may have: 
> * Oliver Beckstein (talk to him in person or email orbeckst@mdanalysis.org or call +1 480 727 9765 or `@orbeckst` on Discord)
> * Jenna Swarthout Goddard (email: , `@jennaswa` on Discord) 
> * Irfan Alibay (talk to him in person or email: , `@highspeedmode` on Discord)
> 

you can add my ialibay@mdanalysis.org email there if needed - that's public enough and I will be looking at it regularly

**Comment by jennaswa** [comment]
Yes, feel free to list community@mdanalysis.org as my contact email.

**Comment by jennaswa** [comment]
Closed with https://github.com/MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day/pull/29
