### ISSUE TITLE
add Health & Safety

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day#21]
- [x] Add the section https://www.mdanalysis.org/pages/ugm2024/#health-and-safety to the information
- [x] get some testing kits + spare masks

**Comment by orbeckst** [comment]
oops, pushed changes directly to the live-branch... sorry

@jennaswa if you get a chance, can you please look at https://github.com/MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day?tab=readme-ov-file#health-and-safety and let me know if we need to change/update anything.

Note:
- I used UGM 2024 as basis.
- We will have testing kits (9x2) and masks (60).
- I removed the section on social distancing because we don't have enough space to give people the option.
- I added a section on letting us know about positive tests via workshop@mdanalysis.org. We promise to keep it confidential but we will inform the attendees that someone had a positive result.

**Comment by jennaswa** [comment]
LGTM - thanks, @orbeckst !
