### ISSUE TITLE
Update material for MDAnalysis Part 1/2

### ISSUE THREAD

**Issue by fiona-naughton** [MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day#3]

**Comment by jennaswa** [comment]
@IAlibay - When you are able to make updates to materials for parts 1 and 2, please note that some changes that were made for the [February MDA/Molecular Nodes workshop](https://github.com/MDAnalysis/MDAnalysisWorkshop-Intro0.5Day) and [outstanding issues from the TYC workshop](https://github.com/MDAnalysis/MDAnalysisWorkshop-Intro1Day/issues) have not yet been incorporated into Lectures 1/2 and Tutorials 1/2 in this current repo.

You can take or leave these changes as you wish, but wanted to point you to them as something to double-check.
