### ISSUE TITLE
Update materials for MDAnalysis Part 3

### ISSUE THREAD

**Issue by fiona-naughton** [MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day#4]

**Comment by jennaswa** [comment]
@yuxuanzhuang - Please note the known [issue that the links to the user guide/docs are broken](https://github.com/MDAnalysis/MDAnalysisWorkshop-Intro1Day/issues/14) in Tutorial 3. Please make sure to point these to the stable versions when you are updating the materials for Part 3.
