### ISSUE TITLE
Update materials for MDAnalysis Part 4

### ISSUE THREAD

**Issue by fiona-naughton** [MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day#5]

**Comment by jennaswa** [comment]
@fiona-naughton - Please note the known [issue that the links to the user guide/docs are broken](https://github.com/MDAnalysis/MDAnalysisWorkshop-Intro1Day/issues/14) in Tutorial 4. Please make sure to point these to the stable versions when you are updating the materials for Part 4.
