### ISSUE TITLE
Update MolSSI materials

### ISSUE THREAD

**Issue by jennaswa** [MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day#9]
@armcdona and @sjayellis - I have linked to publicly available lessons for the MolSSI sessions (Intro to bash shell; Version control; Python packaging; Testing; Documentation) in the [README schedule](https://github.com/MDAnalysis/MDAnalysisMolSSIWorkshop-Intermediate2Day?tab=readme-ov-file#schedule). 

However, please update these links if there are materials specific to this workshop that you will be referencing. For example, we will want to make sure the Python packaging materials link to the MDAnalysis cookie cutter and [example kit, mdgeomkit](https://github.com/MDAnalysis/mdgeomkit), somewhere.

**Comment by sjayellis** [comment]
I have opened a PR, #17, to have links for each MolSSI lesson that also links to the example mdgeomkit and the MDAnalysis cookiecutter.
